name: daily-update
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call iKon API
        run: |
          curl \
          --url 'https://mnvt.vercel.app/api/tweet' \
          --header 'x-mnvaccinetracker-key: ${{ secrets.API_KEY }}'

