name: daily-update
on:
  schedule:
    - cron: '55 2 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger serverless function
        run: |
          curl -s https://mnvt.vercel.app/api/tweet --header 'x-mnvaccinetracker-key: ${{ secrets.API_KEY }}'
